/* player/quiz_data.js - English Word Quiz Dataset (Original Order with New Additions at the Bottom) */

const QUIZ_WORDS = [
    /* === [Original Dataset - 원본 순서 유지] === */
    { word: "apple", meaning: "사과" },
    { word: "bag", meaning: "가방" },
    { word: "banana", meaning: "바나나" },
    { word: "bear", meaning: "곰, 견디다" },
    { word: "big", meaning: "큰" },
    { word: "birthday", meaning: "생일" },
    { word: "book", meaning: "책, 예약하다" },
    { word: "bye", meaning: "안녕, 잘 가" },
    { word: "can", meaning: "할 수 있다, 캔, 통조림" },
    { word: "cat", meaning: "고양이" },
    { word: "chair", meaning: "의자" },
    { word: "chicken", meaning: "닭, 치킨" },
    { word: "close", meaning: "닫다, 가까운, 친밀한" },
    { word: "cold", meaning: "추운, 감기" },
    { word: "come", meaning: "오다" },
    { word: "cow", meaning: "소, 젖소" },
    { word: "dad", meaning: "아빠" },
    { word: "dance", meaning: "춤추다" },
    { word: "desk", meaning: "책상" },
    { word: "dog", meaning: "개, 강아지" },
    { word: "door", meaning: "문" },
    { word: "down", meaning: "아래로, 우울한" },
    { word: "draw", meaning: "그리다, 비기다, 당기다" },
    { word: "everyone", meaning: "모두, 여러분" },
    { word: "eye", meaning: "눈" },
    { word: "face", meaning: "얼굴, 마주보다, 직면하다" },
    { word: "fish", meaning: "물고기, 생선" },
    { word: "fly", meaning: "날다, 파리" },
    { word: "for", meaning: "~을 위해, ~ 동안" },
    { word: "glove", meaning: "장갑" },
    { word: "go", meaning: "가다" },
    { word: "grapes", meaning: "포도" },
    { word: "great", meaning: "훌륭한, 멋진, 위대한" },
    { word: "hand", meaning: "손, 건네주다" },
    { word: "happy", meaning: "행복한" },
    { word: "have", meaning: "가지고 있다, 먹다" },
    { word: "hello", meaning: "안녕, 안녕하세요" },
    { word: "help", meaning: "돕다, 도움, 도움이 되다" },
    { word: "here", meaning: "여기" },
    { word: "hi", meaning: "안녕" },
    { word: "how", meaning: "어떻게, 얼마나" },
    { word: "hungry", meaning: "배고픈" },
    { word: "it", meaning: "그것" },
    { word: "jump", meaning: "뛰다, 점프하다" },
    { word: "kangaroo", meaning: "캥거루" },
    { word: "like", meaning: "좋아하다, ~처럼, 비슷한" },
    { word: "lion", meaning: "사자" },
    { word: "look", meaning: "보다, 보이다" },
    { word: "lunch", meaning: "점심, 점심식사" },
    { word: "make", meaning: "만들다" },
    { word: "many", meaning: "많은" },
    { word: "mom", meaning: "엄마" },
    { word: "monkey", meaning: "원숭이" },
    { word: "mouth", meaning: "입" },
    { word: "name", meaning: "이름, 이름을 짓다" },
    { word: "no", meaning: "아니요" },
    { word: "nose", meaning: "코" },
    { word: "ok", meaning: "괜찮은, 좋은" },
    { word: "on", meaning: "~ 위에, 계속해서" },
    { word: "open", meaning: "열다, 열린" },
    { word: "orange", meaning: "오렌지, 오렌지색" },
    { word: "outside", meaning: "밖에, 밖에서, 외부" },
    { word: "pants", meaning: "바지" },
    { word: "pear", meaning: "배" },
    { word: "pen", meaning: "펜" },
    { word: "pencil", meaning: "연필" },
    { word: "pig", meaning: "돼지" },
    { word: "please", meaning: "제발, 부디, 기쁘게 하다" },
    { word: "point", meaning: "가리키다, 점수, 요점" },
    { word: "put", meaning: "놓다, 두다" },
    { word: "ruler", meaning: "자, 통치자" },
    { word: "run", meaning: "달리다, 운영하다" },
    { word: "shoe", meaning: "신발" },
    { word: "sit", meaning: "앉다" },
    { word: "skate", meaning: "스케이트 타다" },
    { word: "ski", meaning: "스키 타다" },
    { word: "small", meaning: "작은" },
    { word: "snow", meaning: "눈, 눈이 내리다" },
    { word: "snowman", meaning: "눈사람" },
    { word: "sorry", meaning: "미안한, 유감스러운" },
    { word: "stand", meaning: "서다, 참다, 견디다" },
    { word: "sure", meaning: "물론, 확신하는, 확실한" },
    { word: "sweater", meaning: "스웨터" },
    { word: "swim", meaning: "수영하다" },
    { word: "thank", meaning: "감사하다" },
    { word: "that", meaning: "저것, 저" },
    { word: "this", meaning: "이것, 이" },
    { word: "time", meaning: "시간, 번, 횟수" },
    { word: "too", meaning: "또한, 너무" },
    { word: "touch", meaning: "만지다, 감동시키다" },
    { word: "up", meaning: "위로, 완전히" },
    { word: "wait", meaning: "기다리다" },
    { word: "wash", meaning: "씻다, 세탁하다" },
    { word: "welcome", meaning: "환영하다, 반가운" },
    { word: "window", meaning: "창문" },
    { word: "what", meaning: "무엇, 어떤" },
    { word: "yes", meaning: "예" },
    { word: "you", meaning: "너, 당신" },
    { word: "need", meaning: "필요하다, 필요, 욕구" },
    { word: "root", meaning: "뿌리, 근원" },
    { word: "sunlight", meaning: "햇빛" },
    { word: "take care of", meaning: "~을 돌보다" },
    { word: "take in", meaning: "~을 흡수하다, 섭취하다" },
    { word: "thicker", meaning: "더 굵은, 더 두꺼운" },
    { word: "through", meaning: "~을 통해, ~의 곳곳으로" },
    { word: "trunk", meaning: "나무줄기, 여행용 가방, 코끼리 코" },
    { word: "try", meaning: "노력하다, 시도하다" },
    { word: "water", meaning: "물, 물을 주다" },
    { word: "even", meaning: "훨씬, 심지어, 평평한" },
    { word: "food", meaning: "음식, 식량, 양분" },
    { word: "get", meaning: "얻다, 받다, 되다" },
    { word: "grow", meaning: "자라다, 성장하다, 재배하다" },
    { word: "hard", meaning: "어려운, 단단한, 열심히" },
    { word: "help", meaning: "돕다, 도움, 도움이 되다" },
    { word: "leaf [leaves]", meaning: "잎, 나뭇잎" },
    { word: "longer", meaning: "더 긴, 더 길게" },
    { word: "move", meaning: "움직이다, 이동시키다, 이사하다" },

    /* === [New Additions - 이미지 1, 2, 3 추가분 하단 배치] === */
    { word: "activity", meaning: "활동, 사용 기록 (예: 게임 이용 내역)" },
    { word: "asleep", meaning: "잠이 든, 자고 있는" },
    { word: "bedtime", meaning: "잘 시간, 취침 시간" },
    { word: "before", meaning: "~ 전에, ~의 앞에" },
    { word: "brain", meaning: "뇌, 두뇌, (불빛으로 자극받는) 머리" },
    { word: "bring", meaning: "가져오다, 가져다주다 (예: 데운 우유를 가져다주다)" },
    { word: "call", meaning: "큰 소리로 부르다, (~라고) 부르다, 전화하다" },
    { word: "check", meaning: "점검하다, 확인하다, 체크하다" },
    { word: "check on", meaning: "(~의 안부 또는 상태를) 확인하다, 보살피다" },
    { word: "drink", meaning: "마시다, 음료" },
    { word: "later", meaning: "나중에, 이따가" },
    { word: "light", meaning: "빛, 불빛, (뇌를) 깨우는 불빛" },
    { word: "play", meaning: "(게임)을 하다, 놀다, 재생하다" },
    { word: "relax", meaning: "긴장을 풀다, 편안하게 쉬다, 완화하다" },
    { word: "robot", meaning: "로봇, 인공지능 로봇" },
    { word: "screen", meaning: "화면, 액정, 스크린" },
    { word: "sleepy", meaning: "졸린, 잠오는" },
    { word: "soon", meaning: "곧, 금방" },
    { word: "wake up", meaning: "잠에서 깨우다, 깨어나다, 활성화하다" },
    { word: "warm", meaning: "따뜻한, 데운, 따스하게 하다" },
    { word: "watch", meaning: "(주의 깊게) 보다, 지켜보다, 손목시계" },
    { word: "work", meaning: "효과가 있다, (방법 등이) 먹히다, 일하다" }
];
