/* player/quiz_data.js - English Word Quiz Dataset (Original Order with New Additions at the Bottom) 
 * 
 * 💡 퀴즈 단어 및 스케줄러 데이터셋을 수정하거나 추가할 때는 반드시 아래 가이드 문서를 
 *    함께 참고하여 최신 상태를 유지해 주시기 바랍니다:
 *    - 가이드 파일: [quiz_vocabulary_schedule.md](quiz_vocabulary_schedule.md)
 */

const QUIZ_WORDS_BY_DATE = {
    "260612": [
        { word: "apple", meaning: "사과" },
        { word: "banana", meaning: "바나나" },
        { word: "cherry", meaning: "체리" },
        { word: "grape", meaning: "포도" },
        { word: "orange", meaning: "오렌지" }
    ],
    "260531": [
        { word: "activity", meaning: "활동, 사용 기록 (예: 게임 이용 내역)" },
        { word: "asleep", meaning: "잠이 든, 자고 있는" },
        { word: "bedtime", meaning: "잘 시간, 취침 시간" },
        { word: "before", meaning: "~ 전에, ~의 앞에" },
        { word: "brain", meaning: "뇌, 두뇌, (불빛으로 자극받는) 머리" },
        { word: "bring", meaning: "가져오다, 가져다주다 (예: 데운 우유를 가져다주다)" },
        { word: "call", meaning: "큰 소리로 부르다, (~라고) 부르다, 전화하다" },
        { word: "check", meaning: "점검하다, 확인하다, 체크하다" },
        { word: "check on", meaning: "(~의 안부 또는 상태를) 확인하다, 보살피다" },
        { word: "drink", meaning: "마시다, 음료" },
        { word: "later", meaning: "나중에, 이따가" },
        { word: "light", meaning: "빛, 불빛, (뇌를) 깨우는 불빛" },
        { word: "play", meaning: "(게임)을 하다, 놀다, 재생하다" },
        { word: "relax", meaning: "긴장을 풀다, 편안하게 쉬다, 완화하다" },
        { word: "robot", meaning: "로봇, 인공지능 로봇" },
        { word: "screen", meaning: "화면, 액정, 스크린" },
        { word: "sleepy", meaning: "졸린, 잠오는" },
        { word: "soon", meaning: "곧, 금방" },
        { word: "wake up", meaning: "잠에서 깨우다, 깨어나다, 활성화하다" },
        { word: "warm", meaning: "따뜻한, 데운, 따스하게 하다" },
        { word: "watch", meaning: "주의 깊게 보다, 지켜보다, 손목시계" },
        { word: "work", meaning: "효과가 있다, 방법 등이 먹히다, 일하다" }
    ],
    "260602": [
        { word: "awake", meaning: "깨어 있는" },
        { word: "camp", meaning: "캠프" },
        { word: "cool", meaning: "시원한" },
        { word: "difficult", meaning: "어려운" },
        { word: "doze off", meaning: "깜빡 졸다" },
        { word: "explore", meaning: "탐험하다" },
        { word: "fall asleep", meaning: "잠들다" },
        { word: "first", meaning: "첫 번째의" },
        { word: "forest", meaning: "숲" },
        { word: "keep [kept]", meaning: "계속 ~하다" },
        { word: "last", meaning: "지난, 바로 이전의" },
        { word: "loud", meaning: "시끄러운" },
        { word: "luckily", meaning: "다행히" },
        { word: "meet [met]", meaning: "만나다" },
        { word: "problem", meaning: "문제" },
        { word: "quiet", meaning: "조용한" },
        { word: "stormy", meaning: "폭풍우가 치는" },
        { word: "strange", meaning: "이상한" },
        { word: "thunderstorm", meaning: "뇌우 (천둥과 번개를 동반한 비)" },
        { word: "tired", meaning: "피곤한" },
        { word: "weekend", meaning: "주말" },
        { word: "year", meaning: "년, 해" }
    ],
    "260606": [
        { word: "away", meaning: "다른 곳으로" },
        { word: "blow", meaning: "불다" },
        { word: "breathe", meaning: "내뿜다" },
        { word: "dragon", meaning: "용" },
        { word: "early", meaning: "일찍" },
        { word: "easily", meaning: "쉽게" },
        { word: "fire", meaning: "불" },
        { word: "get", meaning: "(잠을) 취하다" },
        { word: "get ready", meaning: "준비하다" },
        { word: "hit", meaning: "맞히다" },
        { word: "important", meaning: "중요한" },
        { word: "need", meaning: "필요하다" },
        { word: "night", meaning: "밤" },
        { word: "only", meaning: "오직" },
        { word: "practice", meaning: "연습하다" },
        { word: "race", meaning: "경주" },
        { word: "sleep", meaning: "잠" },
        { word: "smoke", meaning: "연기" },
        { word: "target", meaning: "표적" },
        { word: "try", meaning: "노력하다" },
        { word: "turn", meaning: "차례, 순서" },
        { word: "win", meaning: "이기다" }
    ],
    "260609": [
        { word: "pet", meaning: "애완동물" },
        { word: "place", meaning: "장소, 곳" },
        { word: "pond", meaning: "연못" },
        { word: "protect", meaning: "보호하다" },
        { word: "put", meaning: "바르다" },
        { word: "shell", meaning: "껍데기" },
        { word: "slime", meaning: "점액" },
        { word: "snail", meaning: "달팽이" },
        { word: "summer", meaning: "여름" },
        { word: "weather", meaning: "날씨" },
        { word: "wet", meaning: "젖은" },
        { word: "around", meaning: "주위에" },
        { word: "boring", meaning: "지루한" },
        { word: "bottom", meaning: "바닥" },
        { word: "end", meaning: "끝나다" },
        { word: "hole", meaning: "구멍" },
        { word: "hope", meaning: "바라다" },
        { word: "in fact", meaning: "사실" },
        { word: "interesting", meaning: "재미있는" },
        { word: "live", meaning: "살다" },
        { word: "moist", meaning: "촉촉한" },
        { word: "most", meaning: "대부분의" }
    ],
    "260613": [
        { word: "aloud", meaning: "소리 내어" },
        { word: "another", meaning: "또 다른" },
        { word: "bell", meaning: "종" },
        { word: "burst", meaning: "불쑥 나오다" },
        { word: "cardboard", meaning: "판지 (두껍고 단단한 종이)" },
        { word: "check", meaning: "확인하다" },
        { word: "class", meaning: "반 학생들" },
        { word: "clock", meaning: "시계" },
        { word: "cube", meaning: "정육면체" },
        { word: "enter", meaning: "들어오다" },
        { word: "expect", meaning: "기다리다" },
        { word: "explain", meaning: "설명하다" },
        { word: "find", meaning: "발견하다" },
        { word: "globe", meaning: "지구본" },
        { word: "ignore", meaning: "무시하다" },
        { word: "look for", meaning: "찾아보다" },
        { word: "note", meaning: "메모" },
        { word: "notice", meaning: "알아차리다" },
        { word: "ring", meaning: "울리다" },
        { word: "sphere", meaning: "구" },
        { word: "tick", meaning: "째깍거리다" },
        { word: "wait", meaning: "기다리다" }
    ],
    "260616": [
        { word: "piece", meaning: "장 (종이를 세는 단위)" },
        { word: "ready", meaning: "준비된" },
        { word: "rectangle", meaning: "직사각형" },
        { word: "right", meaning: "오른쪽의" },
        { word: "shape", meaning: "도형" },
        { word: "side", meaning: "변 (도형에서 각을 만드는 직선)" },
        { word: "square", meaning: "정사각형" },
        { word: "start", meaning: "시작하다" },
        { word: "triangle", meaning: "삼각형" },
        { word: "way", meaning: "방향" },
        { word: "wing", meaning: "날개" },
        { word: "airplane", meaning: "비행기" },
        { word: "center", meaning: "가운데" },
        { word: "corner", meaning: "모서리" },
        { word: "equal", meaning: "똑같은" },
        { word: "fold", meaning: "접다" },
        { word: "half", meaning: "반" },
        { word: "left", meaning: "왼쪽의" },
        { word: "longer", meaning: "더 긴" },
        { word: "open", meaning: "펼치다" },
        { word: "outside", meaning: "바깥쪽의" },
        { word: "paper", meaning: "종이" }
    ],
    "260620": [
        { word: "make", meaning: "① 만들다 ② ~하게 만들다" },
        { word: "medium", meaning: "중간의" },
        { word: "mouth", meaning: "입" },
        { word: "nose", meaning: "코" },
        { word: "pretty", meaning: "꽤, 제법" },
        { word: "size", meaning: "크기" },
        { word: "smaller", meaning: "더 작은" },
        { word: "stick", meaning: "내밀다" },
        { word: "through", meaning: "~을 통해" },
        { word: "tiny", meaning: "아주 작은" },
        { word: "tongue", meaning: "혀" },
        { word: "add", meaning: "추가하다" },
        { word: "bet", meaning: "확신하다" },
        { word: "circle", meaning: "원" },
        { word: "cut out", meaning: "오려 내다" },
        { word: "different", meaning: "다양한" },
        { word: "draw", meaning: "그리다" },
        { word: "ear", meaning: "귀" },
        { word: "finally", meaning: "마지막으로" },
        { word: "hold", meaning: "들다" },
        { word: "hole", meaning: "구멍" },
        { word: "laugh", meaning: "웃다" }
    ],
    "260623": [
        { word: "sailboat", meaning: "요트, 범선" },
        { word: "shape", meaning: "형태, 모양" },
        { word: "soon", meaning: "곧" },
        { word: "spaceship", meaning: "우주선" },
        { word: "special", meaning: "특별한" },
        { word: "sphere", meaning: "구" },
        { word: "tell", meaning: "말하다" },
        { word: "tour", meaning: "여행, 관광" },
        { word: "turn", meaning: "돌다" },
        { word: "unique", meaning: "독특한" },
        { word: "wave", meaning: "파도" },
        { word: "become", meaning: "~이 되다" },
        { word: "building", meaning: "건물" },
        { word: "corner", meaning: "모퉁이" },
        { word: "describe", meaning: "묘사하다" },
        { word: "explain", meaning: "설명하다" },
        { word: "glass", meaning: "유리" },
        { word: "guess", meaning: "① 추측하다 ② 추측" },
        { word: "guide", meaning: "안내자, 가이드" },
        { word: "huge", meaning: "거대한" },
        { word: "look like", meaning: "~처럼 생기다" },
        { word: "pineapple", meaning: "파인애플" }
    ],
    "260627": [
        { word: "afterschool", meaning: "방과 후" },
        { word: "again", meaning: "다시" },
        { word: "ask", meaning: "묻다" },
        { word: "call", meaning: "전화하다" },
        { word: "daily", meaning: "일일, 매일의" },
        { word: "detail", meaning: "세부 사항" },
        { word: "explain", meaning: "설명하다" },
        { word: "forget", meaning: "잊다" },
        { word: "holiday", meaning: "휴일" },
        { word: "hour", meaning: "시간" },
        { word: "later", meaning: "후에" },
        { word: "leave", meaning: "남기다" },
        { word: "math", meaning: "수학" },
        { word: "message", meaning: "메시지" },
        { word: "movie", meaning: "영화" },
        { word: "planner", meaning: "일정표, 계획표" },
        { word: "reply", meaning: "대답하다" },
        { word: "see", meaning: "보다" },
        { word: "sigh", meaning: "한숨을 쉬다" },
        { word: "study", meaning: "공부하다" },
        { word: "take", meaning: "꺼내다" },
        { word: "then", meaning: "그 다음에" }
    ],
    "260630": [
        { word: "a lot of", meaning: "많은" },
        { word: "at", meaning: "(특정 시각) ~에" },
        { word: "can", meaning: "할 수 있다" },
        { word: "clock", meaning: "시계" },
        { word: "do", meaning: "하다" },
        { word: "explain", meaning: "설명하다" },
        { word: "first", meaning: "먼저" },
        { word: "have", meaning: "(해야 할 ~이) 있다" },
        { word: "homework", meaning: "숙제" },
        { word: "how", meaning: "얼마나" },
        { word: "long", meaning: "오래" },
        { word: "meet", meaning: "만나다" },
        { word: "need", meaning: "해야 하다" },
        { word: "or", meaning: "아니면, 혹은" },
        { word: "over", meaning: "~을 통해" },
        { word: "plan", meaning: "계획" },
        { word: "science", meaning: "과학" },
        { word: "see", meaning: "보다" },
        { word: "start", meaning: "시작하다" },
        { word: "take", meaning: "(시간이) 걸리다" },
        { word: "tell", meaning: "말하다" },
        { word: "too", meaning: "~도 역시" }
    ],
    "260704": [
        { word: "agree", meaning: "~하기로 (합의)하다" },
        { word: "annoyed", meaning: "짜증이 난" },
        { word: "arrive", meaning: "도착하다" },
        { word: "care", meaning: "신경 쓰다" },
        { word: "cinema", meaning: "영화관" },
        { word: "dear", meaning: "(편지 첫 부분의 이름 앞에 써서) ~에게" },
        { word: "diary", meaning: "일기" },
        { word: "get [got]", meaning: "받다" },
        { word: "go [went]", meaning: "가다" },
        { word: "late", meaning: "늦은" },
        { word: "look for", meaning: "찾아보다" },
        { word: "people", meaning: "사람들" },
        { word: "person", meaning: "사람" },
        { word: "polite", meaning: "예의 바른" },
        { word: "pretty", meaning: "꽤" },
        { word: "realize", meaning: "깨닫다" },
        { word: "show", meaning: "보여주다" },
        { word: "terrible", meaning: "심각한" },
        { word: "theater", meaning: "극장" },
        { word: "there", meaning: "거기에" },
        { word: "wait", meaning: "기다리다" },
        { word: "yet", meaning: "아직" }
    ],
    "260707": [
        { word: "awake", meaning: "깨어 있는" },
        { word: "call", meaning: "(새·동물의) 울음소리" },
        { word: "coop", meaning: "닭장" },
        { word: "crow", meaning: "(수탉이) 울다" },
        { word: "dawn", meaning: "새벽" },
        { word: "early", meaning: "이른" },
        { word: "easy", meaning: "쉬운" },
        { word: "famous", meaning: "유명한" },
        { word: "hear", meaning: "듣다" },
        { word: "hen", meaning: "암탉" },
        { word: "however", meaning: "하지만" },
        { word: "job", meaning: "임무" },
        { word: "mine", meaning: "나의 것" },
        { word: "morning", meaning: "아침" },
        { word: "nature", meaning: "자연" },
        { word: "on duty", meaning: "임무 수행 중, 일을 하고 있는" },
        { word: "protect", meaning: "보호하다" },
        { word: "quiet", meaning: "조용한" },
        { word: "rooster", meaning: "수탉" },
        { word: "stay away", meaning: "접근하지 않다, 가까이 가지 않다" },
        { word: "wake-up call", meaning: "모닝콜" },
        { word: "worry", meaning: "걱정하다" }
    ],
    "260711": [
        { word: "colorful", meaning: "화려한" },
        { word: "cry", meaning: "울다" },
        { word: "dance", meaning: "춤" },
        { word: "fall", meaning: "넘어지다" },
        { word: "feel", meaning: "느끼다" },
        { word: "feel like", meaning: "~하고 싶다" },
        { word: "get to", meaning: "~에 도착하다" },
        { word: "happen", meaning: "(~일이) 일어나다" },
        { word: "imagine", meaning: "상상하다" },
        { word: "invite", meaning: "초대하다" },
        { word: "just", meaning: "방금, 직전에" },
        { word: "learn", meaning: "배우다" },
        { word: "mean", meaning: "의미하다" },
        { word: "mood", meaning: "기분" },
        { word: "move", meaning: "동작, 움직임" },
        { word: "nervous", meaning: "긴장한, 불안한" },
        { word: "parent", meaning: "아버지(부) 또는 어머니(모) 중 한 명" },
        { word: "poster", meaning: "포스터" },
        { word: "practice", meaning: "연습하다" },
        { word: "show", meaning: "(뮤지컬, 연극 등의) 쇼" },
        { word: "studio", meaning: "(춤, 음악 등의) 연습실" },
        { word: "trip", meaning: "발이 걸리다" }
    ],
    "260714": [
        { word: "arrive", meaning: "(때·행사일 등이) 되다, 도래하다" },
        { word: "ask", meaning: "묻다, 요청하다" },
        { word: "at first", meaning: "처음에는" },
        { word: "believe in", meaning: "~을 믿다" },
        { word: "bravo", meaning: "브라보 (칭찬의 표현)" },
        { word: "cheer", meaning: "환호하다" },
        { word: "everyone", meaning: "모두" },
        { word: "finish", meaning: "끝내다" },
        { word: "hard", meaning: "열심히" },
        { word: "mistake", meaning: "실수" },
        { word: "next", meaning: "다음의" },
        { word: "no one", meaning: "아무도 ~ 않다" },
        { word: "pretend", meaning: "~인 척하다" },
        { word: "proud", meaning: "자랑스러운" },
        { word: "skip", meaning: "거르다, 빼먹다, 빠지다" },
        { word: "smile", meaning: "미소 짓다" },
        { word: "stage", meaning: "무대" },
        { word: "stay behind", meaning: "뒤에 남다" },
        { word: "still", meaning: "여전히" },
        { word: "stop", meaning: "멈추다" },
        { word: "worry", meaning: "걱정하다" },
        { word: "yourself", meaning: "너 자신" }
    ],
    "260718": [
        { word: "about", meaning: "~에 대해서" },
        { word: "around", meaning: "~ 주위를" },
        { word: "baby", meaning: "아기" },
        { word: "different", meaning: "다른" },
        { word: "excited", meaning: "신이 난" },
        { word: "feel", meaning: "느끼다" },
        { word: "get up", meaning: "일어나다" },
        { word: "have", meaning: "(아기를) 낳다" },
        { word: "just", meaning: "그냥, 단순히" },
        { word: "move", meaning: "움직이다" },
        { word: "never", meaning: "결코 ~ 않다" },
        { word: "news", meaning: "소식" },
        { word: "one day", meaning: "어느 날" },
        { word: "quiet", meaning: "조용한" },
        { word: "same", meaning: "같은" },
        { word: "show", meaning: "보여주다" },
        { word: "slowly", meaning: "천천히" },
        { word: "twirl", meaning: "빙글빙글 돌다" },
        { word: "walk", meaning: "걷다" },
        { word: "watch", meaning: "보다, 지켜보다" },
        { word: "way", meaning: "방식, 방법" },
        { word: "whisper", meaning: "속삭이다" }
    ],
    "260721": [
        { word: "back and forth", meaning: "앞뒤로" },
        { word: "best", meaning: "최고의" },
        { word: "bright", meaning: "밝은, 선명한" },
        { word: "closely", meaning: "자세히" },
        { word: "dance", meaning: "춤추다" },
        { word: "dancer", meaning: "댄서, 춤꾼" },
        { word: "fan", meaning: "부채" },
        { word: "feather", meaning: "깃털" },
        { word: "female", meaning: "암컷" },
        { word: "flap", meaning: "(날개를) 퍼덕이다" },
        { word: "flash", meaning: "반짝이는 빛, 번쩍임" },
        { word: "hop", meaning: "깡충 뛰다" },
        { word: "jungle", meaning: "정글, 밀림" },
        { word: "male", meaning: "수컷" },
        { word: "perform", meaning: "~을 행하다, 공연하다" },
        { word: "pick", meaning: "선택하다, 고르다" },
        { word: "shake", meaning: "흔들다" },
        { word: "special", meaning: "특별한" },
        { word: "spread", meaning: "펼치다" },
        { word: "strong", meaning: "강한" },
        { word: "wiggle", meaning: "씰룩씰룩 움직이다" },
        { word: "wing", meaning: "날개" }
    ],
    "260802": [
        { word: "behind", meaning: "뒤에" },
        { word: "call", meaning: "부르다" },
        { word: "drink", meaning: "마시다" },
        { word: "elf", meaning: "작은 요정" },
        { word: "fairy", meaning: "날개 달린 요정" },
        { word: "game", meaning: "놀이" },
        { word: "giant", meaning: "거인" },
        { word: "hide", meaning: "숨다" },
        { word: "invisible", meaning: "보이지 않는" },
        { word: "later", meaning: "나중에" },
        { word: "lose", meaning: "(시합, 게임에서) 지다" },
        { word: "month", meaning: "달, 개월" },
        { word: "next time", meaning: "다음에" },
        { word: "potion", meaning: "묘약, (마법의) 물약" },
        { word: "return", meaning: "돌아가다" },
        { word: "rock", meaning: "바위" },
        { word: "stand", meaning: "서 있다" },
        { word: "try", meaning: "시도하다" },
        { word: "turn", meaning: "(~하게) 변하다" },
        { word: "turn back", meaning: "되돌리다" },
        { word: "wait", meaning: "기다리다" },
        { word: "wizard", meaning: "마법사" }
    ],
    "260804": [
        { word: "afternoon", meaning: "오후" },
        { word: "all", meaning: "내내" },
        { word: "amazed", meaning: "놀란" },
        { word: "anyone", meaning: "아무도" },
        { word: "both", meaning: "둘 다" },
        { word: "circle", meaning: "원" },
        { word: "direction", meaning: "방향" },
        { word: "each other", meaning: "서로" },
        { word: "end", meaning: "끝" },
        { word: "face", meaning: "마주보다" },
        { word: "hold", meaning: "잡다" },
        { word: "hop", meaning: "깡충 뛰다" },
        { word: "jump rope", meaning: "줄넘기를 하다" },
        { word: "just", meaning: "방금" },
        { word: "move", meaning: "이사하다" },
        { word: "opposite", meaning: "반대의" },
        { word: "rope", meaning: "(줄넘기의) 줄, 밧줄" },
        { word: "show", meaning: "보여주다" },
        { word: "spin", meaning: "돌다" },
        { word: "sure", meaning: "물론" },
        { word: "swing", meaning: "돌리다" },
        { word: "yet", meaning: "아직" }
    ],
    "260806": [
        { word: "aim", meaning: "겨냥하다" },
        { word: "anyway", meaning: "어쨌든" },
        { word: "dodgeball", meaning: "피구" },
        { word: "even if", meaning: "~ 하더라도" },
        { word: "excited", meaning: "흥분한" },
        { word: "from now on", meaning: "지금부터" },
        { word: "grip", meaning: "움켜잡다" },
        { word: "hard", meaning: "세게" },
        { word: "hold", meaning: "잡다, 쥐다" },
        { word: "important", meaning: "중요한" },
        { word: "laugh", meaning: "웃다" },
        { word: "loudly", meaning: "큰 소리로" },
        { word: "mean", meaning: "심술궂은, 못된" },
        { word: "other", meaning: "다른" },
        { word: "pain", meaning: "고통" },
        { word: "team", meaning: "팀" },
        { word: "throw", meaning: "던지다" },
        { word: "tightly", meaning: "단단히, 꽉" },
        { word: "too", meaning: "너무" },
        { word: "want", meaning: "원하다" },
        { word: "well", meaning: "잘" },
        { word: "yell", meaning: "외치다, 소리치다" }
    ],
    "260811": [
        { word: "balance", meaning: "균형잡다" },
        { word: "body", meaning: "신체, 몸" },
        { word: "brave", meaning: "용감한" },
        { word: "bridge", meaning: "다리" },
        { word: "challenge", meaning: "도전하다" },
        { word: "climb", meaning: "오르다" },
        { word: "course", meaning: "코스, 과정" },
        { word: "develop", meaning: "발달시키다" },
        { word: "focus", meaning: "집중하다" },
        { word: "great", meaning: "대단한" },
        { word: "high", meaning: "① 높이 있는 ② 높이" },
        { word: "ladder", meaning: "사다리" },
        { word: "learn", meaning: "배우다" },
        { word: "mind", meaning: "정신" },
        { word: "must", meaning: "~해야 하다" },
        { word: "practice", meaning: "연습하다" },
        { word: "rope", meaning: "밧줄" },
        { word: "stronger", meaning: "더 강한" },
        { word: "wobbly", meaning: "흔들리는" },
        { word: "workout", meaning: "운동" },
        { word: "yourself", meaning: "네 자신" },
        { word: "zipline", meaning: "짚라인" }
    ],
    "260813": [
        { word: "answer", meaning: "답" },
        { word: "come down", meaning: "내려오다" },
        { word: "complete", meaning: "완성하다" },
        { word: "congratulations", meaning: "축하해(요)" },
        { word: "divide", meaning: "나누다" },
        { word: "each", meaning: "각각의" },
        { word: "figure out", meaning: "알아내다" },
        { word: "find [found]", meaning: "찾다" },
        { word: "finish", meaning: "끝내다, 다하다" },
        { word: "give up", meaning: "포기하다" },
        { word: "go up", meaning: "올라가다" },
        { word: "group", meaning: "조, 그룹" },
        { word: "letter", meaning: "글자" },
        { word: "never", meaning: "결코 ~ 않다" },
        { word: "puzzle", meaning: "(조각 맞추기) 퍼즐" },
        { word: "rain", meaning: "비" },
        { word: "riddle", meaning: "수수께끼" },
        { word: "shout", meaning: "외치다" },
        { word: "smile", meaning: "미소 짓다" },
        { word: "solve", meaning: "(수수께끼를) 풀다" },
        { word: "together", meaning: "함께, 같이" },
        { word: "work", meaning: "노력하다" }
    ],
    "260818": [
        { word: "cooperate", meaning: "협동하다" },
        { word: "cry", meaning: "외치다" },
        { word: "every day", meaning: "매일" },
        { word: "frown", meaning: "얼굴을 찌푸리다" },
        { word: "goal", meaning: "골, 득점" },
        { word: "hang one's head", meaning: "(부끄러워서) 고개를 숙이다" },
        { word: "important", meaning: "중요한" },
        { word: "know", meaning: "알다" },
        { word: "lose [lost]", meaning: "(시합에서) 지다" },
        { word: "matter", meaning: "중요하다" },
        { word: "pass", meaning: "패스하다" },
        { word: "player", meaning: "운동선수, 선수" },
        { word: "real", meaning: "진정한" },
        { word: "score", meaning: "① (골을) 넣다 ② 점수" },
        { word: "soccer", meaning: "축구" },
        { word: "teamwork", meaning: "협동심, 팀워크" },
        { word: "terrible", meaning: "형편없는" },
        { word: "too", meaning: "너무" },
        { word: "tournament", meaning: "대회 (토너먼트)" },
        { word: "well", meaning: "잘" },
        { word: "win", meaning: "이기다" },
        { word: "winner", meaning: "승자" }
    ],
    "260820": [
        { word: "ask", meaning: "묻다" },
        { word: "assignment", meaning: "과제" },
        { word: "band", meaning: "밴드" },
        { word: "blame", meaning: "탓하다" },
        { word: "complain", meaning: "불평하다" },
        { word: "composition", meaning: "(음악·미술·문학 등의) 작품" },
        { word: "everyone", meaning: "모두" },
        { word: "harmony", meaning: "화음" },
        { word: "hear", meaning: "(들려오는 소리를) 듣다" },
        { word: "leave [left]", meaning: "남다" },
        { word: "listen", meaning: "(귀 기울여) 듣다" },
        { word: "musician", meaning: "음악가" },
        { word: "noise", meaning: "소음" },
        { word: "perfect", meaning: "완벽한" },
        { word: "point", meaning: "핵심" },
        { word: "room", meaning: "~실 (방)" },
        { word: "seem", meaning: "~한 것 같다" },
        { word: "shame", meaning: "아쉬운 일" },
        { word: "sound", meaning: "소리" },
        { word: "talented", meaning: "재능이 뛰어난" },
        { word: "this time", meaning: "이번에는" },
        { word: "walk out", meaning: "밖으로 나가다" }
    ],
    "260825": [
        { word: "block", meaning: "덩어리" },
        { word: "call", meaning: "부르다" },
        { word: "catch", meaning: "잡다" },
        { word: "example", meaning: "예" },
        { word: "fall", meaning: "떨어지다" },
        { word: "float", meaning: "떠다니다" },
        { word: "group", meaning: "무리, 떼" },
        { word: "hunt", meaning: "사냥하다" },
        { word: "killer whale", meaning: "범고래 (흰색과 검정색을 띠는 육식 고래)" },
        { word: "meal", meaning: "식사" },
        { word: "near", meaning: "~ 가까이에, ~ 근처에" },
        { word: "quickly", meaning: "빠르게" },
        { word: "rest", meaning: "휴식하다, 쉬다" },
        { word: "sea", meaning: "바다" },
        { word: "seal", meaning: "바다표범, 물개" },
        { word: "shake", meaning: "흔들다" },
        { word: "share", meaning: "나누다" },
        { word: "split up", meaning: "흩어지다" },
        { word: "swim", meaning: "수영하다" },
        { word: "the South Pole", meaning: "남극" },
        { word: "toward", meaning: "~ 쪽으로" },
        { word: "wave", meaning: "파도" }
    ],
    "260830": [
        { word: "ad", meaning: "광고" },
        { word: "angrily", meaning: "화나서" },
        { word: "art museum", meaning: "미술관" },
        { word: "beautiful", meaning: "아름다운" },
        { word: "boring", meaning: "지루한" },
        { word: "bug", meaning: "벌레" },
        { word: "check", meaning: "확인하다" },
        { word: "city", meaning: "시, 도시" },
        { word: "class", meaning: "수업" },
        { word: "country", meaning: "시골" },
        { word: "date", meaning: "날짜" },
        { word: "daughter", meaning: "딸" },
        { word: "dirty", meaning: "더러운" },
        { word: "everywhere", meaning: "사방에" },
        { word: "farm", meaning: "농장" },
        { word: "frown", meaning: "찡그리다" },
        { word: "garden", meaning: "정원" },
        { word: "help", meaning: "도움" },
        { word: "out", meaning: "저 멀리" },
        { word: "promise", meaning: "약속하다" },
        { word: "then", meaning: "그때" },
        { word: "uncle", meaning: "삼촌" }
    ],
    "260901": [
        { word: "beauty", meaning: "아름다움" },
        { word: "brush", meaning: "붓" },
        { word: "canvas", meaning: "캔버스 (표면에 그림을 그릴 수 있는 천)" },
        { word: "dig up", meaning: "(땅에서) 파내다" },
        { word: "easel", meaning: "이젤 (캔버스 받침대)" },
        { word: "finish", meaning: "마치다" },
        { word: "first", meaning: "처음의" },
        { word: "hand", meaning: "건네주다" },
        { word: "here", meaning: "여기" },
        { word: "hoe", meaning: "괭이" },
        { word: "hour", meaning: "시간" },
        { word: "just", meaning: "단지, 그냥" },
        { word: "leave", meaning: "떠나다" },
        { word: "look at", meaning: "~을 보다" },
        { word: "paint", meaning: "① 그림을 그리다 ② 물감" },
        { word: "reach for", meaning: "~을 향해 손을 뻗다" },
        { word: "smile", meaning: "미소 짓다" },
        { word: "take", meaning: "(시간이) 걸리다" },
        { word: "teach", meaning: "가르치다" },
        { word: "use", meaning: "사용하다" },
        { word: "weed", meaning: "잡초" },
        { word: "whole", meaning: "꼬박" }
    ],
    "260905": [
        { word: "balcony", meaning: "발코니" },
        { word: "box", meaning: "상자" },
        { word: "container", meaning: "(~을 담는) 용기" },
        { word: "different", meaning: "다른" },
        { word: "dirt", meaning: "흙" },
        { word: "each", meaning: "각각의" },
        { word: "fertilizer", meaning: "비료" },
        { word: "grow", meaning: "자라다" },
        { word: "handful", meaning: "한 움큼" },
        { word: "list", meaning: "목록" },
        { word: "little", meaning: "작은" },
        { word: "look over", meaning: "훑어보다" },
        { word: "month", meaning: "달, 월" },
        { word: "person", meaning: "사람" },
        { word: "pull out", meaning: "끄집어내다" },
        { word: "seed", meaning: "씨앗" },
        { word: "several", meaning: "여러 개의" },
        { word: "sprout", meaning: "새싹" },
        { word: "still", meaning: "여전히" },
        { word: "surprised", meaning: "놀란" },
        { word: "worm", meaning: "지렁이" },
        { word: "wriggle", meaning: "꿈틀거리다" }
    ],
    "260908": [
        { word: "benefit", meaning: "유익하다" },
        { word: "care for", meaning: "~을 돌보다" },
        { word: "clothes", meaning: "옷" },
        { word: "cook", meaning: "요리하다" },
        { word: "countryside", meaning: "시골" },
        { word: "couple", meaning: "두어 개의" },
        { word: "creative", meaning: "창의적인" },
        { word: "creativity", meaning: "창의성" },
        { word: "feed", meaning: "먹이다" },
        { word: "focus on", meaning: "~에 중점을 두다" },
        { word: "fruit", meaning: "과일" },
        { word: "grade", meaning: "성적" },
        { word: "instead of", meaning: "~ 대신에" },
        { word: "less", meaning: "더 적게" },
        { word: "nature", meaning: "자연" },
        { word: "outdoor", meaning: "야외의" },
        { word: "respect", meaning: "존중하다" },
        { word: "stressful", meaning: "스트레스가 많은" },
        { word: "take", meaning: "(수업을) 듣다" },
        { word: "theater", meaning: "연극" },
        { word: "vegetable", meaning: "채소" },
        { word: "way", meaning: "방법" }
    ],
    "260912": [
        { word: "amazed", meaning: "놀란" },
        { word: "amazing", meaning: "놀라운" },
        { word: "bring", meaning: "가져오다" },
        { word: "building", meaning: "건물" },
        { word: "climb", meaning: "오르다" },
        { word: "cloud", meaning: "구름" },
        { word: "come back", meaning: "돌아오다" },
        { word: "cut through", meaning: "~ 사이로 길을 내며 나아가다" },
        { word: "discover", meaning: "발견하다" },
        { word: "finally", meaning: "마침내" },
        { word: "fit together", meaning: "들어맞다" },
        { word: "guide", meaning: "가이드, 안내인" },
        { word: "hard", meaning: "힘든" },
        { word: "lost", meaning: "잃어버린" },
        { word: "mountaintop", meaning: "산꼭대기" },
        { word: "perfectly", meaning: "완벽하게" },
        { word: "reach", meaning: "도착하다" },
        { word: "ruins", meaning: "유적" },
        { word: "secret", meaning: "비밀" },
        { word: "stone", meaning: "돌" },
        { word: "thick", meaning: "빽빽한" },
        { word: "unlock", meaning: "(비밀을) 밝히다" }
    ],
    "260915": [
        { word: "announce", meaning: "알리다" },
        { word: "bigger", meaning: "더 큰" },
        { word: "block", meaning: "덩어리" },
        { word: "driver", meaning: "운전기사" },
        { word: "drop open", meaning: "(입이) 벌어지다" },
        { word: "grumble", meaning: "투덜거리다" },
        { word: "hurry off", meaning: "서둘러 내리다" },
        { word: "look", meaning: "① 쳐다보다 ② 보이다" },
        { word: "look out", meaning: "~ 밖을 내다보다" },
        { word: "main", meaning: "가장 큰" },
        { word: "open wide", meaning: "휘둥그레지다" },
        { word: "over", meaning: "끝난" },
        { word: "parent", meaning: "아버지(부) 또는 어머니(모) 중 한 명" },
        { word: "pyramid", meaning: "피라미드" },
        { word: "stack up", meaning: "차곡차곡 쌓이다" },
        { word: "story", meaning: "(건물의) 층" },
        { word: "tall", meaning: "높은" },
        { word: "tour", meaning: "관광" },
        { word: "trip", meaning: "여행" },
        { word: "unforgettable", meaning: "잊을 수 없는" },
        { word: "up close", meaning: "바로 가까이에서" },
        { word: "window", meaning: "창문" }
    ],
    "260919": [
        { word: "admire", meaning: "감탄하다" },
        { word: "ago", meaning: "(얼마의 시간) 전에" },
        { word: "build [built]", meaning: "(건물을) 짓다" },
        { word: "carving", meaning: "조각품" },
        { word: "gate", meaning: "출입문" },
        { word: "giant", meaning: "거대한" },
        { word: "hall", meaning: "복도" },
        { word: "lost", meaning: "길을 잃은" },
        { word: "maze", meaning: "미로" },
        { word: "monk", meaning: "승려" },
        { word: "old", meaning: "오래된" },
        { word: "orange", meaning: "주황색의" },
        { word: "pass", meaning: "지나가다" },
        { word: "place", meaning: "곳" },
        { word: "pointed", meaning: "뾰족한" },
        { word: "robe", meaning: "승복 (승려가 입는 옷)" },
        { word: "sculpture", meaning: "조각상" },
        { word: "temple", meaning: "사원" },
        { word: "tower", meaning: "탑" },
        { word: "visit", meaning: "방문" },
        { word: "world", meaning: "세계" },
        { word: "young", meaning: "젊은" }
    ],
    "260922": [
        { word: "about", meaning: "약, 대략" },
        { word: "believe", meaning: "믿다" },
        { word: "calendar", meaning: "달력" },
        { word: "ceremony", meaning: "의식 (정해진 방식에 따라 치르는 행사)" },
        { word: "circle", meaning: "원" },
        { word: "England", meaning: "영국" },
        { word: "famous", meaning: "유명한" },
        { word: "group", meaning: "무리, 집단" },
        { word: "huge", meaning: "거대한" },
        { word: "inner", meaning: "안쪽의" },
        { word: "inside", meaning: "안에" },
        { word: "long ago", meaning: "오래 전에" },
        { word: "mystery", meaning: "신비, 수수께끼" },
        { word: "outer", meaning: "바깥쪽의" },
        { word: "purpose", meaning: "목적" },
        { word: "rock", meaning: "바위" },
        { word: "special", meaning: "특별한" },
        { word: "stand", meaning: "서 있다" },
        { word: "today", meaning: "오늘날" },
        { word: "watch", meaning: "관찰하다" },
        { word: "wide", meaning: "폭이 ~인" },
        { word: "wonder", meaning: "궁금해하다" }
    ]
};

const QUIZ_WORDS = [
    /* === [Original Dataset - 원본 순서 유지] === */
    { word: "apple", meaning: "사과" },
    { word: "bag", meaning: "가방" },
    { word: "banana", meaning: "바나나" },
    { word: "bear", meaning: "곰, 견디다" },
    { word: "big", meaning: "큰" },
    { word: "birthday", meaning: "생일" },
    { word: "book", meaning: "책, 예약하다" },
    { word: "bye", meaning: "안녕, 잘 가" },
    { word: "can", meaning: "할 수 있다, 캔, 통조림" },
    { word: "cat", meaning: "고양이" },
    { word: "chair", meaning: "의자" },
    { word: "chicken", meaning: "닭, 치킨" },
    { word: "close", meaning: "닫다, 가까운, 친밀한" },
    { word: "cold", meaning: "추운, 감기" },
    { word: "come", meaning: "오다" },
    { word: "cow", meaning: "소, 젖소" },
    { word: "dad", meaning: "아빠" },
    { word: "dance", meaning: "춤추다" },
    { word: "desk", meaning: "책상" },
    { word: "dog", meaning: "개, 강아지" },
    { word: "door", meaning: "문" },
    { word: "down", meaning: "아래로, 우울한" },
    { word: "draw", meaning: "그리다, 비기다, 당기다" },
    { word: "everyone", meaning: "모두, 여러분" },
    { word: "eye", meaning: "눈" },
    { word: "face", meaning: "얼굴, 마주보다, 직면하다" },
    { word: "fish", meaning: "물고기, 생선" },
    { word: "fly", meaning: "날다, 파리" },
    { word: "for", meaning: "~을 위해, ~ 동안" },
    { word: "glove", meaning: "장갑" },
    { word: "go", meaning: "가다" },
    { word: "grapes", meaning: "포도" },
    { word: "great", meaning: "훌륭한, 멋진, 위대한" },
    { word: "hand", meaning: "손, 건네주다" },
    { word: "happy", meaning: "행복한" },
    { word: "have", meaning: "가지고 있다, 먹다" },
    { word: "hello", meaning: "안녕, 안녕하세요" },
    { word: "help", meaning: "돕다, 도움, 도움이 되다" },
    { word: "here", meaning: "여기" },
    { word: "hi", meaning: "안녕" },
    { word: "how", meaning: "어떻게, 얼마나" },
    { word: "hungry", meaning: "배고픈" },
    { word: "it", meaning: "그것" },
    { word: "jump", meaning: "뛰다, 점프하다" },
    { word: "kangaroo", meaning: "캥거루" },
    { word: "like", meaning: "좋아하다, ~처럼, 비슷한" },
    { word: "lion", meaning: "사자" },
    { word: "look", meaning: "보다, 보이다" },
    { word: "lunch", meaning: "점심, 점심식사" },
    { word: "make", meaning: "만들다" },
    { word: "many", meaning: "많은" },
    { word: "mom", meaning: "엄마" },
    { word: "monkey", meaning: "원숭이" },
    { word: "mouth", meaning: "입" },
    { word: "name", meaning: "이름, 이름을 짓다" },
    { word: "no", meaning: "아니요" },
    { word: "nose", meaning: "코" },
    { word: "ok", meaning: "괜찮은, 좋은" },
    { word: "on", meaning: "~ 위에, 계속해서" },
    { word: "open", meaning: "열다, 열린" },
    { word: "orange", meaning: "오렌지, 오렌지색" },
    { word: "outside", meaning: "밖에, 밖에서, 외부" },
    { word: "pants", meaning: "바지" },
    { word: "pear", meaning: "배" },
    { word: "pen", meaning: "펜" },
    { word: "pencil", meaning: "연필" },
    { word: "pig", meaning: "돼지" },
    { word: "please", meaning: "제발, 부디, 기쁘게 하다" },
    { word: "point", meaning: "가리키다, 점수, 요점" },
    { word: "put", meaning: "놓다, 두다" },
    { word: "ruler", meaning: "자, 통치자" },
    { word: "run", meaning: "달리다, 운영하다" },
    { word: "shoe", meaning: "신발" },
    { word: "sit", meaning: "앉다" },
    { word: "skate", meaning: "스케이트 타다" },
    { word: "ski", meaning: "스키 타다" },
    { word: "small", meaning: "작은" },
    { word: "snow", meaning: "눈, 눈이 내리다" },
    { word: "snowman", meaning: "눈사람" },
    { word: "sorry", meaning: "미안한, 유감스러운" },
    { word: "stand", meaning: "서다, 참다, 견디다" },
    { word: "sure", meaning: "물론, 확신하는, 확실한" },
    { word: "sweater", meaning: "스웨터" },
    { word: "swim", meaning: "수영하다" },
    { word: "thank", meaning: "감사하다" },
    { word: "that", meaning: "저것, 저" },
    { word: "this", meaning: "이것, 이" },
    { word: "time", meaning: "시간, 번, 횟수" },
    { word: "too", meaning: "또한, 너무" },
    { word: "touch", meaning: "만지다, 감동시키다" },
    { word: "up", meaning: "위로, 완전히" },
    { word: "wait", meaning: "기다리다" },
    { word: "wash", meaning: "씻다, 세탁하다" },
    { word: "welcome", meaning: "환영하다, 반가운" },
    { word: "window", meaning: "창문" },
    { word: "what", meaning: "무엇, 어떤" },
    { word: "yes", meaning: "예" },
    { word: "you", meaning: "너, 당신" },
    { word: "need", meaning: "필요하다, 필요, 욕구" },
    { word: "root", meaning: "뿌리, 근원" },
    { word: "sunlight", meaning: "햇빛" },
    { word: "take care of", meaning: "~을 돌보다" },
    { word: "take in", meaning: "~을 흡수하다, 섭취하다" },
    { word: "thicker", meaning: "더 굵은, 더 두꺼운" },
    { word: "through", meaning: "~을 통해, ~의 곳곳으로" },
    { word: "trunk", meaning: "나무줄기, 여행용 가방, 코끼리 코" },
    { word: "try", meaning: "노력하다, 시도하다" },
    { word: "water", meaning: "물, 물을 주다" },
    { word: "even", meaning: "훨씬, 심지어, 평평한" },
    { word: "food", meaning: "음식, 식량, 양분" },
    { word: "get", meaning: "얻다, 받다, 되다" },
    { word: "grow", meaning: "자라다, 성장하다, 재배하다" },
    { word: "hard", meaning: "어려운, 단단한, 열심히" },
    { word: "help", meaning: "돕다, 도움, 도움이 되다" },
    { word: "leaf [leaves]", meaning: "잎, 나뭇잎" },
    { word: "longer", meaning: "더 긴, 더 길게" },
    { word: "move", meaning: "움직이다, 이동시키다, 이사하다" },

    /* === [New Additions - 이미지 1, 2, 3 추가분 하단 배치] === */
    { word: "activity", meaning: "활동, 사용 기록 (예: 게임 이용 내역)" },
    { word: "asleep", meaning: "잠이 든, 자고 있는" },
    { word: "bedtime", meaning: "잘 시간, 취침 시간" },
    { word: "before", meaning: "~ 전에, ~의 앞에" },
    { word: "brain", meaning: "뇌, 두뇌, (불빛으로 자극받는) 머리" },
    { word: "bring", meaning: "가져오다, 가져다주다 (예: 데운 우유를 가져다주다)" },
    { word: "call", meaning: "큰 소리로 부르다, (~라고) 부르다, 전화하다" },
    { word: "check", meaning: "점검하다, 확인하다, 체크하다" },
    { word: "check on", meaning: "(~의 안부 또는 상태를) 확인하다, 보살피다" },
    { word: "drink", meaning: "마시다, 음료" },
    { word: "later", meaning: "나중에, 이따가" },
    { word: "light", meaning: "빛, 불빛, (뇌를) 깨우는 불빛" },
    { word: "play", meaning: "(게임)을 하다, 놀다, 재생하다" },
    { word: "relax", meaning: "긴장을 풀다, 편안하게 쉬다, 완화하다" },
    { word: "robot", meaning: "로봇, 인공지능 로봇" },
    { word: "screen", meaning: "화면, 액정, 스크린" },
    { word: "sleepy", meaning: "졸린, 잠오는" },
    { word: "soon", meaning: "곧, 금방" },
    { word: "wake up", meaning: "잠에서 깨우다, 깨어나다, 활성화하다" },
    { word: "warm", meaning: "따뜻한, 데운, 따스하게 하다" },
    { word: "watch", meaning: "주의 깊게 보다, 지켜보다, 손목시계" },
    { word: "work", meaning: "효과가 있다, 방법 등이 먹히다, 일하다" },

    /* === [260602 추가분] === */
    { word: "awake", meaning: "깨어 있는" },
    { word: "camp", meaning: "캠프" },
    { word: "cool", meaning: "시원한" },
    { word: "difficult", meaning: "어려운" },
    { word: "doze off", meaning: "깜빡 졸다" },
    { word: "explore", meaning: "탐험하다" },
    { word: "fall asleep", meaning: "잠들다" },
    { word: "first", meaning: "첫 번째의" },
    { word: "forest", meaning: "숲" },
    { word: "keep [kept]", meaning: "계속 ~하다" },
    { word: "last", meaning: "지난, 바로 이전의" },
    { word: "loud", meaning: "시끄러운" },
    { word: "luckily", meaning: "다행히" },
    { word: "meet [met]", meaning: "만나다" },
    { word: "problem", meaning: "문제" },
    { word: "quiet", meaning: "조용한" },
    { word: "stormy", meaning: "폭풍우가 치는" },
    { word: "strange", meaning: "이상한" },
    { word: "thunderstorm", meaning: "뇌우 (천둥과 번개를 동반한 비)" },
    { word: "tired", meaning: "피곤한" },
    { word: "weekend", meaning: "주말" },
    { word: "year", meaning: "년, 해" },

    /* === [260606 추가분] === */
    { word: "away", meaning: "다른 곳으로" },
    { word: "blow", meaning: "불다" },
    { word: "breathe", meaning: "내뿜다" },
    { word: "dragon", meaning: "용" },
    { word: "early", meaning: "일찍" },
    { word: "easily", meaning: "쉽게" },
    { word: "fire", meaning: "불" },
    { word: "get", meaning: "(잠을) 취하다" },
    { word: "get ready", meaning: "준비하다" },
    { word: "hit", meaning: "맞히다" },
    { word: "important", meaning: "중요한" },
    { word: "need", meaning: "필요하다" },
    { word: "night", meaning: "밤" },
    { word: "only", meaning: "오직" },
    { word: "practice", meaning: "연습하다" },
    { word: "race", meaning: "경주" },
    { word: "sleep", meaning: "잠" },
    { word: "smoke", meaning: "연기" },
    { word: "target", meaning: "표적" },
    { word: "try", meaning: "노력하다" },
    { word: "turn", meaning: "차례, 순서" },
    { word: "win", meaning: "이기다" },

    /* === [260609 추가분] === */
    { word: "pet", meaning: "애완동물" },
    { word: "place", meaning: "장소, 곳" },
    { word: "pond", meaning: "연못" },
    { word: "protect", meaning: "보호하다" },
    { word: "put", meaning: "바르다" },
    { word: "shell", meaning: "껍데기" },
    { word: "slime", meaning: "점액" },
    { word: "snail", meaning: "달팽이" },
    { word: "summer", meaning: "여름" },
    { word: "weather", meaning: "날씨" },
    { word: "wet", meaning: "젖은" },
    { word: "around", meaning: "주위에" },
    { word: "boring", meaning: "지루한" },
    { word: "bottom", meaning: "바닥" },
    { word: "end", meaning: "끝나다" },
    { word: "hole", meaning: "구멍" },
    { word: "hope", meaning: "바라다" },
    { word: "in fact", meaning: "사실" },
    { word: "interesting", meaning: "재미있는" },
    { word: "live", meaning: "살다" },
    { word: "moist", meaning: "촉촉한" },
    { word: "most", meaning: "대부분의" },

    /* === [260613 추가분] === */
    { word: "aloud", meaning: "소리 내어" },
    { word: "another", meaning: "또 다른" },
    { word: "bell", meaning: "종" },
    { word: "burst", meaning: "불쑥 나오다" },
    { word: "cardboard", meaning: "판지 (두껍고 단단한 종이)" },
    { word: "check", meaning: "확인하다" },
    { word: "class", meaning: "반 학생들" },
    { word: "clock", meaning: "시계" },
    { word: "cube", meaning: "정육면체" },
    { word: "enter", meaning: "들어오다" },
    { word: "expect", meaning: "기다리다" },
    { word: "explain", meaning: "설명하다" },
    { word: "find", meaning: "발견하다" },
    { word: "globe", meaning: "지구본" },
    { word: "ignore", meaning: "무시하다" },
    { word: "look for", meaning: "찾아보다" },
    { word: "note", meaning: "메모" },
    { word: "notice", meaning: "알아차리다" },
    { word: "ring", meaning: "울리다" },
    { word: "sphere", meaning: "구" },
    { word: "tick", meaning: "째깍거리다" },
    { word: "wait", meaning: "기다리다" },

    /* === [260616 추가분] === */
    { word: "piece", meaning: "장 (종이를 세는 단위)" },
    { word: "ready", meaning: "준비된" },
    { word: "rectangle", meaning: "직사각형" },
    { word: "right", meaning: "오른쪽의" },
    { word: "shape", meaning: "도형" },
    { word: "side", meaning: "변 (도형에서 각을 만드는 직선)" },
    { word: "square", meaning: "정사각형" },
    { word: "start", meaning: "시작하다" },
    { word: "triangle", meaning: "삼각형" },
    { word: "way", meaning: "방향" },
    { word: "wing", meaning: "날개" },
    { word: "airplane", meaning: "비행기" },
    { word: "center", meaning: "가운데" },
    { word: "corner", meaning: "모서리" },
    { word: "equal", meaning: "똑같은" },
    { word: "fold", meaning: "접다" },
    { word: "half", meaning: "반" },
    { word: "left", meaning: "왼쪽의" },
    { word: "longer", meaning: "더 긴" },
    { word: "open", meaning: "펼치다" },
    { word: "outside", meaning: "바깥쪽의" },
    { word: "paper", meaning: "종이" },

    /* === [260620 추가분] === */
    { word: "make", meaning: "① 만들다 ② ~하게 만들다" },
    { word: "medium", meaning: "중간의" },
    { word: "mouth", meaning: "입" },
    { word: "nose", meaning: "코" },
    { word: "pretty", meaning: "꽤, 제법" },
    { word: "size", meaning: "크기" },
    { word: "smaller", meaning: "더 작은" },
    { word: "stick", meaning: "내밀다" },
    { word: "through", meaning: "~을 통해" },
    { word: "tiny", meaning: "아주 작은" },
    { word: "tongue", meaning: "혀" },
    { word: "add", meaning: "추가하다" },
    { word: "bet", meaning: "확신하다" },
    { word: "circle", meaning: "원" },
    { word: "cut out", meaning: "오려 내다" },
    { word: "different", meaning: "다양한" },
    { word: "draw", meaning: "그리다" },
    { word: "ear", meaning: "귀" },
    { word: "finally", meaning: "마지막으로" },
    { word: "hold", meaning: "들다" },
    { word: "hole", meaning: "구멍" },
    { word: "laugh", meaning: "웃다" },

    /* === [260623 추가분] === */
    { word: "sailboat", meaning: "요트, 범선" },
    { word: "shape", meaning: "형태, 모양" },
    { word: "soon", meaning: "곧" },
    { word: "spaceship", meaning: "우주선" },
    { word: "special", meaning: "특별한" },
    { word: "sphere", meaning: "구" },
    { word: "tell", meaning: "말하다" },
    { word: "tour", meaning: "여행, 관광" },
    { word: "turn", meaning: "돌다" },
    { word: "unique", meaning: "독특한" },
    { word: "wave", meaning: "파도" },
    { word: "become", meaning: "~이 되다" },
    { word: "building", meaning: "건물" },
    { word: "corner", meaning: "모퉁이" },
    { word: "describe", meaning: "묘사하다" },
    { word: "explain", meaning: "설명하다" },
    { word: "glass", meaning: "유리" },
    { word: "guess", meaning: "① 추측하다 ② 추측" },
    { word: "guide", meaning: "안내자, 가이드" },
    { word: "huge", meaning: "거대한" },
    { word: "look like", meaning: "~처럼 생기다" },
    { word: "pineapple", meaning: "파인애플" },

    /* === [260626 추가분] === */
    { word: "afterschool", meaning: "방과 후" },
    { word: "again", meaning: "다시" },
    { word: "ask", meaning: "묻다" },
    { word: "call", meaning: "전화하다" },
    { word: "daily", meaning: "일일, 매일의" },
    { word: "detail", meaning: "세부 사항" },
    { word: "explain", meaning: "설명하다" },
    { word: "forget", meaning: "잊다" },
    { word: "holiday", meaning: "휴일" },
    { word: "hour", meaning: "시간" },
    { word: "later", meaning: "후에" },
    { word: "leave", meaning: "남기다" },
    { word: "math", meaning: "수학" },
    { word: "message", meaning: "메시지" },
    { word: "movie", meaning: "영화" },
    { word: "planner", meaning: "일정표, 계획표" },
    { word: "reply", meaning: "대답하다" },
    { word: "see", meaning: "보다" },
    { word: "sigh", meaning: "한숨을 쉬다" },
    { word: "study", meaning: "공부하다" },
    { word: "take", meaning: "꺼내다" },
    { word: "then", meaning: "그 다음에" },

    /* === [260630 추가분] === */
    { word: "a lot of", meaning: "많은" },
    { word: "at", meaning: "(특정 시각) ~에" },
    { word: "can", meaning: "할 수 있다" },
    { word: "clock", meaning: "시계" },
    { word: "do", meaning: "하다" },
    { word: "explain", meaning: "설명하다" },
    { word: "first", meaning: "먼저" },
    { word: "have", meaning: "(해야 할 ~이) 있다" },
    { word: "homework", meaning: "숙제" },
    { word: "how", meaning: "얼마나" },
    { word: "long", meaning: "오래" },
    { word: "meet", meaning: "만나다" },
    { word: "need", meaning: "해야 하다" },
    { word: "or", meaning: "아니면, 혹은" },
    { word: "over", meaning: "~을 통해" },
    { word: "plan", meaning: "계획" },
    { word: "science", meaning: "과학" },
    { word: "see", meaning: "보다" },
    { word: "start", meaning: "시작하다" },
    { word: "take", meaning: "(시간이) 걸리다" },
    { word: "tell", meaning: "말하다" },
    { word: "too", meaning: "~도 역시" },

    /* === [260704 추가분] === */
    { word: "agree", meaning: "~하기로 (합의)하다" },
    { word: "annoyed", meaning: "짜증이 난" },
    { word: "arrive", meaning: "도착하다" },
    { word: "care", meaning: "신경 쓰다" },
    { word: "cinema", meaning: "영화관" },
    { word: "dear", meaning: "(편지 첫 부분의 이름 앞에 써서) ~에게" },
    { word: "diary", meaning: "일기" },
    { word: "get [got]", meaning: "받다" },
    { word: "go [went]", meaning: "가다" },
    { word: "late", meaning: "늦은" },
    { word: "look for", meaning: "찾아보다" },
    { word: "people", meaning: "사람들" },
    { word: "person", meaning: "사람" },
    { word: "polite", meaning: "예의 바른" },
    { word: "pretty", meaning: "꽤" },
    { word: "realize", meaning: "깨닫다" },
    { word: "show", meaning: "보여주다" },
    { word: "terrible", meaning: "심각한" },
    { word: "theater", meaning: "극장" },
    { word: "there", meaning: "거기에" },
    { word: "wait", meaning: "기다리다" },
    { word: "yet", meaning: "아직" },

    /* === [260707 추가분] === */
    { word: "awake", meaning: "깨어 있는" },
    { word: "call", meaning: "(새·동물의) 울음소리" },
    { word: "coop", meaning: "닭장" },
    { word: "crow", meaning: "(수탉이) 울다" },
    { word: "dawn", meaning: "새벽" },
    { word: "early", meaning: "이른" },
    { word: "easy", meaning: "쉬운" },
    { word: "famous", meaning: "유명한" },
    { word: "hear", meaning: "듣다" },
    { word: "hen", meaning: "암탉" },
    { word: "however", meaning: "하지만" },
    { word: "job", meaning: "임무" },
    { word: "mine", meaning: "나의 것" },
    { word: "morning", meaning: "아침" },
    { word: "nature", meaning: "자연" },
    { word: "on duty", meaning: "임무 수행 중, 일을 하고 있는" },
    { word: "protect", meaning: "보호하다" },
    { word: "quiet", meaning: "조용한" },
    { word: "rooster", meaning: "수탉" },
    { word: "stay away", meaning: "접근하지 않다, 가까이 가지 않다" },
    { word: "wake-up call", meaning: "모닝콜" },
    { word: "worry", meaning: "걱정하다" },

    /* === [260711 추가분] === */
    { word: "colorful", meaning: "화려한" },
    { word: "cry", meaning: "울다" },
    { word: "dance", meaning: "춤" },
    { word: "fall", meaning: "넘어지다" },
    { word: "feel", meaning: "느끼다" },
    { word: "feel like", meaning: "~하고 싶다" },
    { word: "get to", meaning: "~에 도착하다" },
    { word: "happen", meaning: "(~일이) 일어나다" },
    { word: "imagine", meaning: "상상하다" },
    { word: "invite", meaning: "초대하다" },
    { word: "just", meaning: "방금, 직전에" },
    { word: "learn", meaning: "배우다" },
    { word: "mean", meaning: "의미하다" },
    { word: "mood", meaning: "기분" },
    { word: "move", meaning: "동작, 움직임" },
    { word: "nervous", meaning: "긴장한, 불안한" },
    { word: "parent", meaning: "아버지(부) 또는 어머니(모) 중 한 명" },
    { word: "poster", meaning: "포스터" },
    { word: "practice", meaning: "연습하다" },
    { word: "show", meaning: "(뮤지컬, 연극 등의) 쇼" },
    { word: "studio", meaning: "(춤, 음악 등의) 연습실" },
    { word: "trip", meaning: "발이 걸리다" },

    /* === [260714 추가분] === */
    { word: "arrive", meaning: "(때·행사일 등이) 되다, 도래하다" },
    { word: "ask", meaning: "묻다, 요청하다" },
    { word: "at first", meaning: "처음에는" },
    { word: "believe in", meaning: "~을 믿다" },
    { word: "bravo", meaning: "브라보 (칭찬의 표현)" },
    { word: "cheer", meaning: "환호하다" },
    { word: "everyone", meaning: "모두" },
    { word: "finish", meaning: "끝내다" },
    { word: "hard", meaning: "열심히" },
    { word: "mistake", meaning: "실수" },
    { word: "next", meaning: "다음의" },
    { word: "no one", meaning: "아무도 ~ 않다" },
    { word: "pretend", meaning: "~인 척하다" },
    { word: "proud", meaning: "자랑스러운" },
    { word: "skip", meaning: "거르다, 빼먹다, 빠지다" },
    { word: "smile", meaning: "미소 짓다" },
    { word: "stage", meaning: "무대" },
    { word: "stay behind", meaning: "뒤에 남다" },
    { word: "still", meaning: "여전히" },
    { word: "stop", meaning: "멈추다" },
    { word: "worry", meaning: "걱정하다" },
    { word: "yourself", meaning: "너 자신" },

    /* === [260718 추가분] === */
    { word: "about", meaning: "~에 대해서" },
    { word: "around", meaning: "~ 주위를" },
    { word: "baby", meaning: "아기" },
    { word: "different", meaning: "다른" },
    { word: "excited", meaning: "신이 난" },
    { word: "feel", meaning: "느끼다" },
    { word: "get up", meaning: "일어나다" },
    { word: "have", meaning: "(아기를) 낳다" },
    { word: "just", meaning: "그냥, 단순히" },
    { word: "move", meaning: "움직이다" },
    { word: "never", meaning: "결코 ~ 않다" },
    { word: "news", meaning: "소식" },
    { word: "one day", meaning: "어느 날" },
    { word: "quiet", meaning: "조용한" },
    { word: "same", meaning: "같은" },
    { word: "show", meaning: "보여주다" },
    { word: "slowly", meaning: "천천히" },
    { word: "twirl", meaning: "빙글빙글 돌다" },
    { word: "walk", meaning: "걷다" },
    { word: "watch", meaning: "보다, 지켜보다" },
    { word: "way", meaning: "방식, 방법" },
    { word: "whisper", meaning: "속삭이다" },

    /* === [260721 추가분] === */
    { word: "back and forth", meaning: "앞뒤로" },
    { word: "best", meaning: "최고의" },
    { word: "bright", meaning: "밝은, 선명한" },
    { word: "closely", meaning: "자세히" },
    { word: "dance", meaning: "춤추다" },
    { word: "dancer", meaning: "댄서, 춤꾼" },
    { word: "fan", meaning: "부채" },
    { word: "feather", meaning: "깃털" },
    { word: "female", meaning: "암컷" },
    { word: "flap", meaning: "(날개를) 퍼덕이다" },
    { word: "flash", meaning: "반짝이는 빛, 번쩍임" },
    { word: "hop", meaning: "깡충 뛰다" },
    { word: "jungle", meaning: "정글, 밀림" },
    { word: "male", meaning: "수컷" },
    { word: "perform", meaning: "~을 행하다, 공연하다" },
    { word: "pick", meaning: "선택하다, 고르다" },
    { word: "shake", meaning: "흔들다" },
    { word: "special", meaning: "특별한" },
    { word: "spread", meaning: "펼치다" },
    { word: "strong", meaning: "강한" },
    { word: "wiggle", meaning: "씰룩씰룩 움직이다" },
    { word: "wing", meaning: "날개" },

    /* === [260802 추가분] === */
    { word: "behind", meaning: "뒤에" },
    { word: "call", meaning: "부르다" },
    { word: "drink", meaning: "마시다" },
    { word: "elf", meaning: "작은 요정" },
    { word: "fairy", meaning: "날개 달린 요정" },
    { word: "game", meaning: "놀이" },
    { word: "giant", meaning: "거인" },
    { word: "hide", meaning: "숨다" },
    { word: "invisible", meaning: "보이지 않는" },
    { word: "later", meaning: "나중에" },
    { word: "lose", meaning: "(시합, 게임에서) 지다" },
    { word: "month", meaning: "달, 개월" },
    { word: "next time", meaning: "다음에" },
    { word: "potion", meaning: "묘약, (마법의) 물약" },
    { word: "return", meaning: "돌아가다" },
    { word: "rock", meaning: "바위" },
    { word: "stand", meaning: "서 있다" },
    { word: "try", meaning: "시도하다" },
    { word: "turn", meaning: "(~하게) 변하다" },
    { word: "turn back", meaning: "되돌리다" },
    { word: "wait", meaning: "기다리다" },
    { word: "wizard", meaning: "마법사" },

    /* === [260804 추가분] === */
    { word: "afternoon", meaning: "오후" },
    { word: "all", meaning: "내내" },
    { word: "amazed", meaning: "놀란" },
    { word: "anyone", meaning: "아무도" },
    { word: "both", meaning: "둘 다" },
    { word: "circle", meaning: "원" },
    { word: "direction", meaning: "방향" },
    { word: "each other", meaning: "서로" },
    { word: "end", meaning: "끝" },
    { word: "face", meaning: "마주보다" },
    { word: "hold", meaning: "잡다" },
    { word: "hop", meaning: "깡충 뛰다" },
    { word: "jump rope", meaning: "줄넘기를 하다" },
    { word: "just", meaning: "방금" },
    { word: "move", meaning: "이사하다" },
    { word: "opposite", meaning: "반대의" },
    { word: "rope", meaning: "(줄넘기의) 줄, 밧줄" },
    { word: "show", meaning: "보여주다" },
    { word: "spin", meaning: "돌다" },
    { word: "sure", meaning: "물론" },
    { word: "swing", meaning: "돌리다" },
    { word: "yet", meaning: "아직" },

    /* === [260806 추가분] === */
    { word: "aim", meaning: "겨냥하다" },
    { word: "anyway", meaning: "어쨌든" },
    { word: "dodgeball", meaning: "피구" },
    { word: "even if", meaning: "~ 하더라도" },
    { word: "excited", meaning: "흥분한" },
    { word: "from now on", meaning: "지금부터" },
    { word: "grip", meaning: "움켜잡다" },
    { word: "hard", meaning: "세게" },
    { word: "hold", meaning: "잡다, 쥐다" },
    { word: "important", meaning: "중요한" },
    { word: "laugh", meaning: "웃다" },
    { word: "loudly", meaning: "큰 소리로" },
    { word: "mean", meaning: "심술궂은, 못된" },
    { word: "other", meaning: "다른" },
    { word: "pain", meaning: "고통" },
    { word: "team", meaning: "팀" },
    { word: "throw", meaning: "던지다" },
    { word: "tightly", meaning: "단단히, 꽉" },
    { word: "too", meaning: "너무" },
    { word: "want", meaning: "원하다" },
    { word: "well", meaning: "잘" },
    { word: "yell", meaning: "외치다, 소리치다" },

    /* === [260811 추가분] === */
    { word: "balance", meaning: "균형잡다" },
    { word: "body", meaning: "신체, 몸" },
    { word: "brave", meaning: "용감한" },
    { word: "bridge", meaning: "다리" },
    { word: "challenge", meaning: "도전하다" },
    { word: "climb", meaning: "오르다" },
    { word: "course", meaning: "코스, 과정" },
    { word: "develop", meaning: "발달시키다" },
    { word: "focus", meaning: "집중하다" },
    { word: "great", meaning: "대단한" },
    { word: "high", meaning: "① 높이 있는 ② 높이" },
    { word: "ladder", meaning: "사다리" },
    { word: "learn", meaning: "배우다" },
    { word: "mind", meaning: "정신" },
    { word: "must", meaning: "~해야 하다" },
    { word: "practice", meaning: "연습하다" },
    { word: "rope", meaning: "밧줄" },
    { word: "stronger", meaning: "더 강한" },
    { word: "wobbly", meaning: "흔들리는" },
    { word: "workout", meaning: "운동" },
    { word: "yourself", meaning: "네 자신" },
    { word: "zipline", meaning: "짚라인" },

    /* === [260813 추가분] === */
    { word: "answer", meaning: "답" },
    { word: "come down", meaning: "내려오다" },
    { word: "complete", meaning: "완성하다" },
    { word: "congratulations", meaning: "축하해(요)" },
    { word: "divide", meaning: "나누다" },
    { word: "each", meaning: "각각의" },
    { word: "figure out", meaning: "알아내다" },
    { word: "find [found]", meaning: "찾다" },
    { word: "finish", meaning: "끝내다, 다하다" },
    { word: "give up", meaning: "포기하다" },
    { word: "go up", meaning: "올라가다" },
    { word: "group", meaning: "조, 그룹" },
    { word: "letter", meaning: "글자" },
    { word: "never", meaning: "결코 ~ 않다" },
    { word: "puzzle", meaning: "(조각 맞추기) 퍼즐" },
    { word: "rain", meaning: "비" },
    { word: "riddle", meaning: "수수께끼" },
    { word: "shout", meaning: "외치다" },
    { word: "smile", meaning: "미소 짓다" },
    { word: "solve", meaning: "(수수께끼를) 풀다" },
    { word: "together", meaning: "함께, 같이" },
    { word: "work", meaning: "노력하다" },

    /* === [260818 추가분] === */
    { word: "cooperate", meaning: "협동하다" },
    { word: "cry", meaning: "외치다" },
    { word: "every day", meaning: "매일" },
    { word: "frown", meaning: "얼굴을 찌푸리다" },
    { word: "goal", meaning: "골, 득점" },
    { word: "hang one's head", meaning: "(부끄러워서) 고개를 숙이다" },
    { word: "important", meaning: "중요한" },
    { word: "know", meaning: "알다" },
    { word: "lose [lost]", meaning: "(시합에서) 지다" },
    { word: "matter", meaning: "중요하다" },
    { word: "pass", meaning: "패스하다" },
    { word: "player", meaning: "운동선수, 선수" },
    { word: "real", meaning: "진정한" },
    { word: "score", meaning: "① (골을) 넣다 ② 점수" },
    { word: "soccer", meaning: "축구" },
    { word: "teamwork", meaning: "협동심, 팀워크" },
    { word: "terrible", meaning: "형편없는" },
    { word: "too", meaning: "너무" },
    { word: "tournament", meaning: "대회 (토너먼트)" },
    { word: "well", meaning: "잘" },
    { word: "win", meaning: "이기다" },
    { word: "winner", meaning: "승자" },

    /* === [260820 추가분] === */
    { word: "ask", meaning: "묻다" },
    { word: "assignment", meaning: "과제" },
    { word: "band", meaning: "밴드" },
    { word: "blame", meaning: "탓하다" },
    { word: "complain", meaning: "불평하다" },
    { word: "composition", meaning: "(음악·미술·문학 등의) 작품" },
    { word: "everyone", meaning: "모두" },
    { word: "harmony", meaning: "화음" },
    { word: "hear", meaning: "(들려오는 소리를) 듣다" },
    { word: "leave [left]", meaning: "남다" },
    { word: "listen", meaning: "(귀 기울여) 듣다" },
    { word: "musician", meaning: "음악가" },
    { word: "noise", meaning: "소음" },
    { word: "perfect", meaning: "완벽한" },
    { word: "point", meaning: "핵심" },
    { word: "room", meaning: "~실 (방)" },
    { word: "seem", meaning: "~한 것 같다" },
    { word: "shame", meaning: "아쉬운 일" },
    { word: "sound", meaning: "소리" },
    { word: "talented", meaning: "재능이 뛰어난" },
    { word: "this time", meaning: "이번에는" },
    { word: "walk out", meaning: "밖으로 나가다" },

    /* === [260825 추가분] === */
    { word: "block", meaning: "덩어리" },
    { word: "call", meaning: "부르다" },
    { word: "catch", meaning: "잡다" },
    { word: "example", meaning: "예" },
    { word: "fall", meaning: "떨어지다" },
    { word: "float", meaning: "떠다니다" },
    { word: "group", meaning: "무리, 떼" },
    { word: "hunt", meaning: "사냥하다" },
    { word: "killer whale", meaning: "범고래 (흰색과 검정색을 띠는 육식 고래)" },
    { word: "meal", meaning: "식사" },
    { word: "near", meaning: "~ 가까이에, ~ 근처에" },
    { word: "quickly", meaning: "빠르게" },
    { word: "rest", meaning: "휴식하다, 쉬다" },
    { word: "sea", meaning: "바다" },
    { word: "seal", meaning: "바다표범, 물개" },
    { word: "shake", meaning: "흔들다" },
    { word: "share", meaning: "나누다" },
    { word: "split up", meaning: "흩어지다" },
    { word: "swim", meaning: "수영하다" },
    { word: "the South Pole", meaning: "남극" },
    { word: "toward", meaning: "~ 쪽으로" },
    { word: "wave", meaning: "파도" },

    /* === [260830 추가분] === */
    { word: "ad", meaning: "광고" },
    { word: "angrily", meaning: "화나서" },
    { word: "art museum", meaning: "미술관" },
    { word: "beautiful", meaning: "아름다운" },
    { word: "boring", meaning: "지루한" },
    { word: "bug", meaning: "벌레" },
    { word: "check", meaning: "확인하다" },
    { word: "city", meaning: "시, 도시" },
    { word: "class", meaning: "수업" },
    { word: "country", meaning: "시골" },
    { word: "date", meaning: "날짜" },
    { word: "daughter", meaning: "딸" },
    { word: "dirty", meaning: "더러운" },
    { word: "everywhere", meaning: "사방에" },
    { word: "farm", meaning: "농장" },
    { word: "frown", meaning: "찡그리다" },
    { word: "garden", meaning: "정원" },
    { word: "help", meaning: "도움" },
    { word: "out", meaning: "저 멀리" },
    { word: "promise", meaning: "약속하다" },
    { word: "then", meaning: "그때" },
    { word: "uncle", meaning: "삼촌" },

    /* === [260901 추가분] === */
    { word: "beauty", meaning: "아름다움" },
    { word: "brush", meaning: "붓" },
    { word: "canvas", meaning: "캔버스 (표면에 그림을 그릴 수 있는 천)" },
    { word: "dig up", meaning: "(땅에서) 파내다" },
    { word: "easel", meaning: "이젤 (캔버스 받침대)" },
    { word: "finish", meaning: "마치다" },
    { word: "first", meaning: "처음의" },
    { word: "hand", meaning: "건네주다" },
    { word: "here", meaning: "여기" },
    { word: "hoe", meaning: "괭이" },
    { word: "hour", meaning: "시간" },
    { word: "just", meaning: "단지, 그냥" },
    { word: "leave", meaning: "떠나다" },
    { word: "look at", meaning: "~을 보다" },
    { word: "paint", meaning: "① 그림을 그리다 ② 물감" },
    { word: "reach for", meaning: "~을 향해 손을 뻗다" },
    { word: "smile", meaning: "미소 짓다" },
    { word: "take", meaning: "(시간이) 걸리다" },
    { word: "teach", meaning: "가르치다" },
    { word: "use", meaning: "사용하다" },
    { word: "weed", meaning: "잡초" },
    { word: "whole", meaning: "꼬박" },

    /* === [260905 추가분] === */
    { word: "balcony", meaning: "발코니" },
    { word: "box", meaning: "상자" },
    { word: "container", meaning: "(~을 담는) 용기" },
    { word: "different", meaning: "다른" },
    { word: "dirt", meaning: "흙" },
    { word: "each", meaning: "각각의" },
    { word: "fertilizer", meaning: "비료" },
    { word: "grow", meaning: "자라다" },
    { word: "handful", meaning: "한 움큼" },
    { word: "list", meaning: "목록" },
    { word: "little", meaning: "작은" },
    { word: "look over", meaning: "훑어보다" },
    { word: "month", meaning: "달, 월" },
    { word: "person", meaning: "사람" },
    { word: "pull out", meaning: "끄집어내다" },
    { word: "seed", meaning: "씨앗" },
    { word: "several", meaning: "여러 개의" },
    { word: "sprout", meaning: "새싹" },
    { word: "still", meaning: "여전히" },
    { word: "surprised", meaning: "놀란" },
    { word: "worm", meaning: "지렁이" },
    { word: "wriggle", meaning: "꿈틀거리다" },

    /* === [260908 추가분] === */
    { word: "benefit", meaning: "유익하다" },
    { word: "care for", meaning: "~을 돌보다" },
    { word: "clothes", meaning: "옷" },
    { word: "cook", meaning: "요리하다" },
    { word: "countryside", meaning: "시골" },
    { word: "couple", meaning: "두어 개의" },
    { word: "creative", meaning: "창의적인" },
    { word: "creativity", meaning: "창의성" },
    { word: "feed", meaning: "먹이다" },
    { word: "focus on", meaning: "~에 중점을 두다" },
    { word: "fruit", meaning: "과일" },
    { word: "grade", meaning: "성적" },
    { word: "instead of", meaning: "~ 대신에" },
    { word: "less", meaning: "더 적게" },
    { word: "nature", meaning: "자연" },
    { word: "outdoor", meaning: "야외의" },
    { word: "respect", meaning: "존중하다" },
    { word: "stressful", meaning: "스트레스가 많은" },
    { word: "take", meaning: "(수업을) 듣다" },
    { word: "theater", meaning: "연극" },
    { word: "vegetable", meaning: "채소" },
    { word: "way", meaning: "방법" },

    /* === [260912 추가분] === */
    { word: "amazed", meaning: "놀란" },
    { word: "amazing", meaning: "놀라운" },
    { word: "bring", meaning: "가져오다" },
    { word: "building", meaning: "건물" },
    { word: "climb", meaning: "오르다" },
    { word: "cloud", meaning: "구름" },
    { word: "come back", meaning: "돌아오다" },
    { word: "cut through", meaning: "~ 사이로 길을 내며 나아가다" },
    { word: "discover", meaning: "발견하다" },
    { word: "finally", meaning: "마침내" },
    { word: "fit together", meaning: "들어맞다" },
    { word: "guide", meaning: "가이드, 안내인" },
    { word: "hard", meaning: "힘든" },
    { word: "lost", meaning: "잃어버린" },
    { word: "mountaintop", meaning: "산꼭대기" },
    { word: "perfectly", meaning: "완벽하게" },
    { word: "reach", meaning: "도착하다" },
    { word: "ruins", meaning: "유적" },
    { word: "secret", meaning: "비밀" },
    { word: "stone", meaning: "돌" },
    { word: "thick", meaning: "빽빽한" },
    { word: "unlock", meaning: "(비밀을) 밝히다" },

    /* === [260915 추가분] === */
    { word: "announce", meaning: "알리다" },
    { word: "bigger", meaning: "더 큰" },
    { word: "block", meaning: "덩어리" },
    { word: "driver", meaning: "운전기사" },
    { word: "drop open", meaning: "(입이) 벌어지다" },
    { word: "grumble", meaning: "투덜거리다" },
    { word: "hurry off", meaning: "서둘러 내리다" },
    { word: "look", meaning: "① 쳐다보다 ② 보이다" },
    { word: "look out", meaning: "~ 밖을 내다보다" },
    { word: "main", meaning: "가장 큰" },
    { word: "open wide", meaning: "휘둥그레지다" },
    { word: "over", meaning: "끝난" },
    { word: "parent", meaning: "아버지(부) 또는 어머니(모) 중 한 명" },
    { word: "pyramid", meaning: "피라미드" },
    { word: "stack up", meaning: "차곡차곡 쌓이다" },
    { word: "story", meaning: "(건물의) 층" },
    { word: "tall", meaning: "높은" },
    { word: "tour", meaning: "관광" },
    { word: "trip", meaning: "여행" },
    { word: "unforgettable", meaning: "잊을 수 없는" },
    { word: "up close", meaning: "바로 가까이에서" },
    { word: "window", meaning: "창문" },

    /* === [260919 추가분] === */
    { word: "admire", meaning: "감탄하다" },
    { word: "ago", meaning: "(얼마의 시간) 전에" },
    { word: "build [built]", meaning: "(건물을) 짓다" },
    { word: "carving", meaning: "조각품" },
    { word: "gate", meaning: "출입문" },
    { word: "giant", meaning: "거대한" },
    { word: "hall", meaning: "복도" },
    { word: "lost", meaning: "길을 잃은" },
    { word: "maze", meaning: "미로" },
    { word: "monk", meaning: "승려" },
    { word: "old", meaning: "오래된" },
    { word: "orange", meaning: "주황색의" },
    { word: "pass", meaning: "지나가다" },
    { word: "place", meaning: "곳" },
    { word: "pointed", meaning: "뾰족한" },
    { word: "robe", meaning: "승복 (승려가 입는 옷)" },
    { word: "sculpture", meaning: "조각상" },
    { word: "temple", meaning: "사원" },
    { word: "tower", meaning: "탑" },
    { word: "visit", meaning: "방문" },
    { word: "world", meaning: "세계" },
    { word: "young", meaning: "젊은" },

    /* === [260922 추가분] === */
    { word: "about", meaning: "약, 대략" },
    { word: "believe", meaning: "믿다" },
    { word: "calendar", meaning: "달력" },
    { word: "ceremony", meaning: "의식 (정해진 방식에 따라 치르는 행사)" },
    { word: "circle", meaning: "원" },
    { word: "England", meaning: "영국" },
    { word: "famous", meaning: "유명한" },
    { word: "group", meaning: "무리, 집단" },
    { word: "huge", meaning: "거대한" },
    { word: "inner", meaning: "안쪽의" },
    { word: "inside", meaning: "안에" },
    { word: "long ago", meaning: "오래 전에" },
    { word: "mystery", meaning: "신비, 수수께끼" },
    { word: "outer", meaning: "바깥쪽의" },
    { word: "purpose", meaning: "목적" },
    { word: "rock", meaning: "바위" },
    { word: "special", meaning: "특별한" },
    { word: "stand", meaning: "서 있다" },
    { word: "today", meaning: "오늘날" },
    { word: "watch", meaning: "관찰하다" },
    { word: "wide", meaning: "폭이 ~인" },
    { word: "wonder", meaning: "궁금해하다" }
];