/* player/quiz_data.js - English Word Quiz Dataset (Extracted from PDF) */

const QUIZ_WORDS = [
    { word: "apple", meaning: "사과" },
    { word: "bag", meaning: "가방" },
    { word: "banana", meaning: "바나나" },
    { word: "bear", meaning: "곰" },
    { word: "big", meaning: "큰" },
    { word: "birthday", meaning: "생일" },
    { word: "book", meaning: "책" },
    { word: "bye", meaning: "안녕 (헤어질 때)" },
    { word: "can", meaning: "할 수 있다" },
    { word: "cat", meaning: "고양이" },
    { word: "chair", meaning: "의자" },
    { word: "chicken", meaning: "닭 (치킨)" },
    { word: "close", meaning: "닫다" },
    { word: "cold", meaning: "추운" },
    { word: "come", meaning: "오다" },
    { word: "cow", meaning: "소 (젖소)" },
    { word: "dad", meaning: "아빠" },
    { word: "dance", meaning: "춤추다" },
    { word: "desk", meaning: "책상" },
    { word: "dog", meaning: "개 (강아지)" },
    { word: "door", meaning: "문" },
    { word: "down", meaning: "아래로" },
    { word: "draw", meaning: "그리다" },
    { word: "everyone", meaning: "모두 (여러분)" },
    { word: "eye", meaning: "눈" },
    { word: "face", meaning: "얼굴" },
    { word: "fish", meaning: "물고기" },
    { word: "fly", meaning: "날다" },
    { word: "for", meaning: "~을 위해" },
    { word: "glove", meaning: "장갑" },
    { word: "go", meaning: "가다" },
    { word: "grapes", meaning: "포도" },
    { word: "great", meaning: "훌륭한 (멋진)" },
    { word: "hand", meaning: "손" },
    { word: "happy", meaning: "행복한" },
    { word: "have", meaning: "가지고 있다" },
    { word: "hello", meaning: "안녕 (만났을 때)" },
    { word: "help", meaning: "돕다" },
    { word: "here", meaning: "여기" },
    { word: "hi", meaning: "안녕 (친근하게)" },
    { word: "how", meaning: "어떻게" },
    { word: "hungry", meaning: "배고픈" },
    { word: "it", meaning: "그것" },
    { word: "jump", meaning: "뛰다 (점프하다)" },
    { word: "kangaroo", meaning: "캥거루" },
    { word: "like", meaning: "좋아하다" },
    { word: "lion", meaning: "사자" },
    { word: "look", meaning: "보다" },
    { word: "lunch", meaning: "점심 (점심식사)" },
    { word: "make", meaning: "만들다" },
    { word: "many", meaning: "많은" },
    { word: "mom", meaning: "엄마" },
    { word: "monkey", meaning: "원숭이" },
    { word: "mouth", meaning: "입" },
    { word: "name", meaning: "이름" },
    { word: "no", meaning: "아니요" },
    { word: "nose", meaning: "코" },
    { word: "ok", meaning: "괜찮은 (좋은)" },
    { word: "on", meaning: "~ 위에" },
    { word: "open", meaning: "열다" },
    { word: "orange", meaning: "오렌지" },
    { word: "outside", meaning: "밖에 (밖에서)" },
    { word: "pants", meaning: "바지" },
    { word: "pear", meaning: "배 (과일)" },
    { word: "pen", meaning: "펜" },
    { word: "pencil", meaning: "연필" },
    { word: "pig", meaning: "돼지" },
    { word: "please", meaning: "제발 (부디)" },
    { word: "point", meaning: "가리키다 (점수)" },
    { word: "put", meaning: "놓다 (두다)" },
    { word: "ruler", meaning: "자" },
    { word: "run", meaning: "달리다" },
    { word: "shoe", meaning: "신발" },
    { word: "sit", meaning: "앉다" },
    { word: "skate", meaning: "스케이트 타다" },
    { word: "ski", meaning: "스키 타다" },
    { word: "small", meaning: "작은" },
    { word: "snow", meaning: "눈 (날씨)" },
    { word: "snowman", meaning: "눈사람" },
    { word: "sorry", meaning: "미안한" },
    { word: "stand", meaning: "서다" },
    { word: "sure", meaning: "물론 (확신하는)" },
    { word: "sweater", meaning: "스웨터" },
    { word: "swim", meaning: "수영하다" },
    { word: "thank", meaning: "감사하다" },
    { word: "that", meaning: "저것 (저)" },
    { word: "this", meaning: "이것 (이)" },
    { word: "time", meaning: "시간" },
    { word: "too", meaning: "또한 (너무)" },
    { word: "touch", meaning: "만지다" },
    { word: "up", meaning: "위로" },
    { word: "wait", meaning: "기다리다" },
    { word: "wash", meaning: "씻다" },
    { word: "welcome", meaning: "환영하다" },
    { word: "window", meaning: "창문" },
    { word: "what", meaning: "무엇" },
    { word: "yes", meaning: "예" },
    { word: "you", meaning: "너 (당신)" },
    { word: "need", meaning: "필요하다" },
    { word: "root", meaning: "뿌리" },
    { word: "sunlight", meaning: "햇빛" },
    { word: "take care of", meaning: "~을 돌보다" },
    { word: "take in", meaning: "~을 흡수하다" },
    { word: "thicker", meaning: "더 굵은" },
    { word: "through", meaning: "~의 곳곳으로" },
    { word: "trunk", meaning: "(나무)줄기" },
    { word: "try", meaning: "노력하다" },
    { word: "water", meaning: "물" },
    { word: "even", meaning: "훨씬, 심지어" },
    { word: "food", meaning: "양분 (나무에 필요한 영양분)" },
    { word: "get", meaning: "(어떤 상태가) 되다" },
    { word: "grow", meaning: "자라다" },
    { word: "hard", meaning: "어려운" },
    { word: "help", meaning: "도움이 되다, 돕다" },
    { word: "leaf [leaves]", meaning: "잎" },
    { word: "longer", meaning: "더 긴" },
    { word: "move", meaning: "이동시키다" }
];
